CREATE VIEW VIEW_USER_INFORMATION AS
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, 
       D1.CITY_NAME AS CURRENT_CITY, D1.STATE_NAME AS CURRENT_STATE, D1.COUNTRY_NAME AS CURRENT_COUNTRY,
       H1.CITY_NAME AS HOMETOWN_CITY, H1.STATE_NAME AS HOMETOWN_STATE, H1.COUNTRY_NAME AS HOMETOWN_COUNTRY, 
       P.INSTITUTION AS INSTITUTION_NAME, E.PROGRAM_YEAR AS PROGRAM_YEAR, 
       P.CONCENTRATION AS PROGRAM_CONCENTRATION, P.DEGREE AS PROGRAM_DEGREE
FROM USERS U
LEFT JOIN USER_CURRENT_CITIES D on D.USER_ID = U.USER_ID
LEFT JOIN USER_HOMETOWN_CITIES H on H.USER_ID = U.USER_ID
LEFT JOIN EDUCATION E on E.USER_ID = U.USER_ID
LEFT JOIN CITIES D1 on D1.CITY_ID = D.CURRENT_CITY_ID
LEFT JOIN CITIES H1 on H1.CITY_ID = H.HOMETOWN_CITY_ID
LEFT JOIN PROGRAMS P on P.PROGRAM_ID = E.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT F.USER1_ID, F.USER2_ID
FROM FRIENDS F;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT P.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME,
       A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME,
       P.PHOTO_LINK
FROM PHOTOS P
LEFT JOIN ALBUMS A on P.ALBUM_ID = A.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE,
       E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME,
       E.EVENT_END_TIME
FROM USER_EVENTS E
LEFT JOIN CITIES C on C.CITY_ID = E.EVENT_CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT T.TAG_PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, T.TAG_X, T.TAG_Y
FROM TAGS T;